### PR TITLE
[minor] Dependency management with poetry

### PR DESCRIPTION
**Pull request by noxan**
## :microscope: Background

- [Poetry](https://python-poetry.org/) is a modern python dependency manager unifying all requirements and distribution related configuration

## :crystal_ball: Key changes

- Review all of our dependencies and remove unused ones (#1201)
- Lock all package version numbers to their latest feature release which is compatible with our minimum python version of `3.7.1` (#911)

## ❓ Discussion points

1. Any reasons not to remove the `requirements/*.txt` setup?

## 📓 Open tasks

1. Migrate the github actions to the new poetry setup (away from pip)

## ✨ Why poetry?

1. It ensures package versions are compatible with the python version
2. Ensures the right package dependency version and their dependencies are installed with its lock-file
3. Automatically manages the virtual environment setup
4. Integrates the publish workflow (pypi)
5. Supports different dependency groups (e.g. `tests`, `docs`) and unifies them all into a single configuration file
6. Easily keep track of all outdated packages (with `poetry list --outdated`) and update them accordingly

### CODE REVIEW

**Comment by ourownstory** [comment]
@noxan I concur that this would be the right thing to do if our package would not be used within other packages or in environments with other packages. 
However, tightening the requirements more than critically necessary will cause issues for libraries such as Darts using our package, as you can see from https://github.com/ourownstory/neural_prophet/issues/1129
Also, users who want to use multiple different models in the same environment may run into issues.

Does poetry allow us to relax, rather than tighten the dependency bounds?

A small point is the familiarity most developers/users have with pip vs poetry.

**Comment by noxan** [comment]
> However, tightening the requirements more than critically necessary will cause issues for libraries such as Darts using our package, as you can see from https://github.com/ourownstory/neural_prophet/issues/1129
Also I agree with your argument of not defining them to tightly as it creates issues. But having unbound dependency versions creates other kinds of issues, e.g. our package breaks if another dependency introduces a breaking change. And in my experience it is better to be explicit about versions, it is easy to report a too tightly bound dependency and relax it. In contrary you can spend hours on figuring out which versions are incompatible, and why which package breaks. Especially if they are not explicitly defined, everything works fine, you recreate your development environment or a new developer joins the team and nothing works anymore - because the dependency versions luckily overlapped during your first project setup, just now things changed and nobody has a clue what...

> Does poetry allow us to relax, rather than tighten the dependency bounds?
How tightly we define our dependencies is independent of poetry or pip. They both allow the same options.

>  Also, users who want to use multiple different models in the same environment may run into issues.
Into what kind of issues? That package versions are not compatible? At least it would be explicit then, good look trying to figure out which exact version of a dependency (3rd party) of your dependencies are incompatible to another.

> A small point is the familiarity most developers/users have with pip vs poetry.
Agree - poetry also makes a lot of things a lot easier

**Comment by noxan** [comment]
@ourownstory 

> However, tightening the requirements more than critically necessary will cause issues for libraries such as Darts using our package, as you can see from https://github.com/ourownstory/neural_prophet/issues/1129

Also I agree with your argument of not defining them to tightly as it creates issues. But having unbound dependency versions creates other kinds of issues, e.g. our package breaks if another dependency introduces a breaking change. And in my experience it is better to be explicit about versions, it is easy to report a too tightly bound dependency and relax it. In contrary you can spend hours on figuring out which versions are incompatible, and why which package breaks. Especially if they are not explicitly defined, everything works fine, you recreate your development environment or a new developer joins the team and nothing works anymore - because the dependency versions luckily overlapped during your first project setup, just now things changed and nobody has a clue what...


> Does poetry allow us to relax, rather than tighten the dependency bounds?

How tightly we define our dependencies is independent of poetry or pip. They both allow the same options.


>  Also, users who want to use multiple different models in the same environment may run into issues.

Into what kind of issues? That package versions are not compatible? At least it would be explicit then, good look trying to figure out which exact version of a dependency (3rd party) of your dependencies are incompatible to another.


> A small point is the familiarity most developers/users have with pip vs poetry.

Agree - yet poetry also makes a lot of things a lot easier

**Comment by noxan** [comment]
Another thing which I became aware of: we use a lot of dependencies which are actually not supporting our python version anymore, e.g. pandas dropped python `3.7` support with version `1.4`. Our requirements allows anything `pandas>=1.0.4` - apparently it still works but how knows for how long they break with python `3.7` - it is not even officially supported anymore.

**Review by LeonieFreisinger — APPROVED** [review]
LGTM @noxan Please have a look at the failing test again

**Pull request merged**
