### PR TITLE
[Minor] Convert timezones to UTC by default

### PR DESCRIPTION
**Pull request by christymctse**
## :microscope: Background

- Fixing issue #970 

## :crystal_ball: Key changes
- Adding UTC as true in the parameter to convert timezone to UTC timestamp
- Removed warning which stated that NP is not supporting timezone specified dataset

## :clipboard: Review Checklist
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, added docstrings and data types to function definitions.
- [x] I have added pytests to check whether my feature / fix works.

Please make sure to follow our best practices in the [Contributing guidelines](https://github.com/ourownstory/neural_prophet/blob/main/CONTRIBUTING.md).

### CODE REVIEW

**Review by noxan — CHANGES_REQUESTED** [review]
While testing with the energy dataset I receive the following issue:
```
AttributeError                            Traceback (most recent call last)
/var/folders/h5/r0lsf_xx0dgf0y4_7tyr6zx80000gn/T/ipykernel_55050/2978023471.py in <module>
      4 )
      5 
----> 6 metrics = m.fit(df)
      7 
      8 forecast = m.predict(df)

neural_prophet/neuralprophet/forecaster.py in fit(self, df, freq, validation_df, epochs, batch_size, learning_rate, early_stopping, minimal, metrics, progress, checkpointing, continue_training, num_workers)
...
    504             return PeriodProperties(data, orig)
    505 
--> 506         raise AttributeError("Can only use .dt accessor with datetimelike values")

AttributeError: Can only use .dt accessor with datetimelike values
```

**Comment by noxan** [comment]
I had a brief look into it, seems https://stackoverflow.com/questions/69020835/attributeerror-can-only-use-dt-accessor-with-datetimelike-values-but-cells-con might be helpful and https://pandas.pydata.org/docs/reference/api/pandas.Series.tz_localize.html

**Comment by noxan** [comment]
Would also be great to have the new code in place where the old code was, so that all checks and transformations on the `ds` column are in the same place.

**Comment by ourownstory** [comment]
@christymctse What's the status on this?

**Comment by christymctse** [comment]
> @christymctse What's the status on this?

Will be working on this next week

**Comment by christymctse** [comment]
@noxan @ourownstory, sorry about get back late
 Just fixed the bug and it should be working fine on the energy dataset now

**Comment by ourownstory** [comment]
@noxan Can you please give this another review to check whether it is ready for merge? Thank you!

**Review by noxan — APPROVED** [review]
Thanks @christymctse for the adjustments, it works for me now - good job 👍

**Pull request merged**
