### PR TITLE
Remove residuals in forecast dataframe returned by m.predict()

### PR DESCRIPTION
**Pull request by judussoari**
*Disabled the plotting option for residuals as well

*Not really needed as residuals are part of basic metrics such as MAE and RMSE

*forecast df is very large, which may overwhelm the user. Now more lean

### CODE REVIEW

**Comment by Kevin-Chen0** [comment]
Can you have it pass the flake8 and metrics test? Thanks.

**Comment by Kevin-Chen0** [comment]
Can you pass the flake8 test by resolving this following issue?

`local variable 'notnull' is assigned to but never used`

**Comment by ourownstory** [comment]
In the future we may add a tutorial on how to analyze residuals and what one can learn from them.

**Review by ourownstory — APPROVED** [review]
LGTM

**Comment by ourownstory** [comment]
fixed merge commits. ready to merge when tests pass.

**Pull request merged**
