### PR TITLE
Adding experiment to MLflow_and_NeuralProphet.ipynb

### PR DESCRIPTION
**Pull request by cargecla1**
Adding example with MLflow Autologging, dataset, requirements & environment metadata with model signature inference

## :microscope: Background

- Why is this change needed? Is there a related issue or a new feature to be added?
- This is to add another way to register and track model relevant information using MLFlow with NeuralProphet

## :crystal_ball: Key changes

- This example allow users to learn how to use MLflow autologging using pytorch function

## :clipboard: Review Checklist
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, added docstrings and data types to function definitions.
- [x] I have added pytests to check whether my feature / fix works.

Please make sure to follow our best practices in the [Contributing guidelines](https://github.com/ourownstory/neural_prophet/blob/main/CONTRIBUTING.md).

### CODE REVIEW

**Comment by cargecla1** [comment]
Hello @SimonWittner,

As previously discussed, I have started a new branch and pull request to add another example to use MLflow with NeuralProphet for your review.

Please refer to: https://github.com/ourownstory/neural_prophet/pull/1499

**Comment by SimonWittner** [comment]
Hey @cargecla1, 
thank you very much for your contribution! 
Maybe I missed it: but how does your example differ from the given one? Is there any additional feature you would like to see in this tutorial? 
Also, could you please adjust the code, so that the tests/docs won't fail? Maybe the best way to do this is to add/use the existing if-loop with the dummy variable 'local'.

**Comment by cargecla1** [comment]
> Hey @cargecla1, thank you very much for your contribution! Maybe I missed it: but how does your example differ from the given one? Is there any additional feature you would like to see in this tutorial? Also, could you please adjust the code, so that the tests/docs won't fail? Maybe the best way to do this is to add/use the existing if-loop with the dummy variable 'local'.

Hello @SimonWittner,

Happy New Year! I just came back from a trip.

I will make the change requested within the next week or so.

WRT the difference, they way I wrote the code is invoking mlflow.pytorch functions which allows you to also save the conda environment used to run the model as well as pip requirements in addition to other metadata (e.g. the hash of the dataset used). In terms of saving the model and logging model hyperparameters it achieves the same in a different way (making different calls which I think it is great for diversity); it is always good to show few ways of doing something. In addition, I show a different way to log metrics, instead of calling all of them one by one, you can use autologin (mlflow.pytorch.autolog).

Hope this helps!

Cheers,

Claudio

**Review by ourownstory — APPROVED** [review]
Thank you for your contribution, it is very welcome!

If you could add some comments explaining the last 4 mlflow commands post the run loop, that'd be fantastic.

**Comment by cargecla1** [comment]
> Thank you for your contribution, it is very welcome!
> 
> If you could add some comments explaining the last 4 mlflow commands post the run loop, that'd be fantastic.

Hello @ourownstory, 
Your welcome! I appreciate your support through the whole process.
I believe I now made the latest changes requested by you and @SimonWittner, but for some reason my new commit doesn't re-run all test. Will you know why? Please advice.

**Comment by ourownstory** [comment]
Great, thank you!
I had a quick look at the updated code and looks good. I wonder though if the call to `mlflow.pytorch.autolog` would need to be moved inside the `local` if statement to avoid issues with the doc test. 

> my new commit doesn't re-run all test. Will you know why? Please advice.

It looks like the auto-merge with main failed with conflicts. Once you resolve this by doing a manual merge, the tests should auto-run.

**Comment by cargecla1** [comment]
> Great, thank you! I had a quick look at the updated code and it looks good. I wonder though if the call to `mlflow.pytorch.autolog` would need to be moved inside the `local` if statement to avoid issues with the doc test.
> 
> > my new commit doesn't re-run all test. Will you know why? Please advice.
> 
> It looks like the auto-merge with main failed with conflicts. Once you resolve this by doing a manual merge, the tests should auto-run.

Hello @ourownstory,

Hope you are well, I tried your suggestion: "I wonder though if the call to `mlflow.pytorch.autolog` would need to be moved inside the `local` if statement to avoid issues with the doc test."

But I am getting below error for the doc test:

"Notebook error:
NoSuchKernel in how-to-guides/feature-guides/MLflow_and_NeuralProphet.ipynb:
No such kernel named python3
Error: Process completed with exit code 2."

I don't know why is no finding a python kernel? Any thoughts/guidance?

Thank you in advance.

**Review by ourownstory — APPROVED** [review]
Looks good, thank you for the updates!

The doc test error may come from before you. We will resolve it separately.

Thank you again!

**Comment by cargecla1** [comment]
> Looks good, thank you for the updates!
> 
> The doc test error may come from before you. We will resolve it separately.
> 
> Thank you again!

Your welcome and thank you for your support with the process.

**Pull request merged**
