### PR TITLE
[Feature] MLflow tutorial

### PR DESCRIPTION
**Pull request by SimonWittner**
## :microscope: Background

- Tutorial for integration of MLflow and NeuralProphet
- Solves #1483 

## :clipboard: Review Checklist
- [X] I have performed a self-review of my own code.
- [X] I have commented my code, added docstrings and data types to function definitions.
- [X] I have added pytests to check whether my feature / fix works.

### CODE REVIEW

**Comment by cargecla1** [comment]
Hello @SimonWittner,  
Please give me a 3-5 few days to share it, it is in my other computer.
I noticed your code is different to mine, you will see, does your code run?. Are you planning to add my code here? or do you want me to add it here (https://github.com/ourownstory/neural_prophet/pull/1487/commits/493c2cfb089416079886a49dacc032c1d2b58e7b#diff-a16afb98e5a4518a7fbf5a90bb9e218cd147d124f30aef3c1c8a6b310db1d3b8) as a commit for your review?

**Comment by cargecla1** [comment]
Hello @SimonWittner,

 I tried to push my changes but I don't have write access, so please see my code below. Is there any chance that you could add me as contributor to this notebook if you add/ merge my code with yours?

Thank you in advance.

#### Example with MLflow Autologging

# MLflow setup
# Run this command with environment activated: mlflow ui --port xxxx  (e.g. 5000, 5001, 5002)
# Copy and paste url from command line to web browser

import mlflow
import torchmetrics
from mlflow.data.pandas_dataset import PandasDataset

mlflow.pytorch.autolog(log_every_n_epoch=1, log_every_n_step=None, 
                        log_models=True, log_datasets=True, disable=False,
                        exclusive=False, disable_for_unsupported_versions=False,
                        silent=False, registered_model_name=None, extra_tags=None
                        )

import mlflow.pytorch
from mlflow.client import MlflowClient

model_name = "NeuralProphet"

with mlflow.start_run() as run:

    dataset: PandasDataset = mlflow.data.from_pandas(df, source="AirPassengersDataset")

    # Log the dataset to the MLflow Run. Specify the "training" context to indicate that the
    # dataset is used for model training
    mlflow.log_input(dataset, context="training")
   
    mlflow.log_param("model_type", "NeuralProphet")
    mlflow.log_param("n_lags", 8)
    mlflow.log_param("ar_layers", [8, 8, 8, 8])
    mlflow.log_param("accelerator", "gpu")

    #To Train 
    # Import the NeuralProphet
    from neuralprophet import NeuralProphet, set_log_level

    # Disable logging messages unless there is an error
    set_log_level("ERROR")

    # Create a NeuralProphet model with default parameters
    m = NeuralProphet(n_lags=8,  
                  ar_layers=[8, 8, 8, 8],
                  trainer_config = {"accelerator":"gpu"})

    # Use static plotly in notebooks
    m.set_plotting_backend("plotly-resampler")

    # Fit the model on the dataset
    metrics = m.fit(df)

    df_future = m.make_future_dataframe(df, n_historic_predictions=48, periods=12)

    # Predict the future
    forecast = m.predict(df_future)



mlflow.metrics.mae()
mlflow.pytorch.get_default_conda_env()
mlflow.pytorch.get_default_pip_requirements()

#Registering model
model_uri = f"runs:/{run.info.run_id}/NeuralProphet_test"
mlflow.register_model(model_uri=model_uri, name=model_name)

**Comment by SimonWittner** [comment]
Hey @cargecla1 
thanks for providing us with your code! I think it would be best, if you could create a PR with your changes/additions once my basic tutorial is merged. With that you will also be automatically listed as a contributor!

**Comment by cargecla1** [comment]
> Hey @cargecla1 thanks for providing us with your code! I think it would be best, if you could create a PR with your changes/additions once my basic tutorial is merged. With that you will also be automatically listed as a contributor!

Hello @SimonWittner,

Sounds good, I will do that. 
Thank you!

**Review by ourownstory — APPROVED** [review]
Great thank you!

**Pull request closed without merging**
