### PR TITLE
[major] Upgrade to PyTorch 2

### PR DESCRIPTION
**Pull request by noxan**
Another attempt to upgrade to PyTorch 2.0

- 2.0.1 seems to be broken due to 
  - https://github.com/python-poetry/poetry/issues/8002 and 
  - https://github.com/pytorch/pytorch/issues/100974
- There is no direct version dependency on Lightning, as stated in the docs: "Is 2.0 code backwards-compatible with 1.X? Yes, using 2.0 will not require you to modify your PyTorch workflows." see point 4 of https://pytorch.org/get-started/pytorch-2.0/#faqs

### CODE REVIEW

**Review by leoniewgnr — APPROVED** [review]
This is amazing, thanks so much Richard!!

**Comment by leoniewgnr** [comment]
@ourownstory what do you think, can we merge that?

**Comment by leoniewgnr** [comment]
> @ourownstory what do you think, can we merge that?

I'll go ahead and merge this now, I think a lot of users are waiting for it.

**Comment by leoniewgnr** [comment]
> @ourownstory what do you think, can we merge that?

I'll go ahead and merge this now, I think a lot of users are waiting for it.

**Comment by leoniewgnr** [comment]
> @ourownstory what do you think, can we merge that?

I'll go ahead and merge this now, I think a lot of users are waiting for it.

**Comment by leoniewgnr** [comment]
@noxan this really is amazing, I always had some dependency issues when installing NP with other packages, everything resolved now!

**Comment by noxan** [comment]
Also wanted to say thank you to @hxyue1 who contributed to this PR kind of behind the scenes and tried several alternative attempts to make this finally work 🙏

**Pull request merged**
