### PR TITLE
[Major] Glocal Modelling v2

### PR DESCRIPTION
**Pull request by alfonsogarciadecorral**
WORK IN PROGRESS

This PR will include a new set of features for Global-Local Modelling:

- [ ] Glocal Trend - To capture both global and local trend information.
>  A test solution is already implemented. We have to translate. Will be done after Trend Modularity PR is pushed
- [x] Different Seasonality modes - To allow using a global yearly seasonality and a local weekly seasonality for example
- [x] Glocal Seasonality - To capture both global and local seasonality information.
- [ ] Static Covariates - To allow local modelling of regressors/covariates/AR.
- [x] Future Regressors - Better modelling of the regressors impact

Once the implementation is done. We will test the model using retail data.

### CODE REVIEW

**Review by ourownstory — APPROVED** [review]
Excellent Work @alfonsogarciadecorral !!
This is a massive contribution and a big upgrade for global-local modeling.
Thank you!

**Comment by ourownstory** [comment]
@leoniewgnr Can you please help @alfonsogarciadecorral to get the tests to run, so we can merge this large PR? The issue does not seem connected to this PR, but rather to poetry? @hxyue1 Can you maybe help figure out if this is a poetry misconfiguration? Thank you so much!

**Comment by alfonsogarciadecorral** [comment]
Hi @leoniewgnr  @hxyue1 ! Just saw this is still not merged, let me know if you have any doubt about anything from the PR!

**Comment by ourownstory** [comment]
@alfonsogarciadecorral I finally got to do a deep-dive and found the bug: A model forward pass in time_net was computing AR components twice - once directly and once after stationarizing. Now the performance metrics match!

**Comment by ourownstory** [comment]
- [ ] Next steps: create new release before merging
- [ ] then merge and create another release with this.

**Pull request merged**
