### PR TITLE
[WIP] Regularization tutorials notebooks

### PR DESCRIPTION
**Pull request by ourownstory**

### CODE REVIEW

**Comment by Kevin-Chen0** [comment]
Is this PR for version 0.5.0?

**Comment by noxan** [comment]
@ourownstory let's have a short chat what this PR is about and what needs to be done to get it ready

**Comment by noxan** [comment]
Related to #723

**Comment by leoniewgnr** [comment]
@noxan is this ready for review?
Who should review?

**Comment by noxan** [comment]
@leoniewgnr I believe this is a draft oskar did a while ago for some regularization notebooks - I didn't touch it 😅

**Comment by leoniewgnr** [comment]
closed for now, but will be revived for v2
until now moved to https://github.com/ourownstory/neural_prophet/wiki/Abandoned-Pull-Requests-and-Issues

**Pull request closed without merging**
