### PR TITLE
# Plolty plot didn't show on colab

### PR DESCRIPTION
**Pull request by vijaybirju**
Plotly plot didn't show on Colab

## :microscope: Background

- This change will let show plolly plots on colab notebook
## :crystal_ball: Key changes

- Explain the main changes introduced by this pull request for the reviewer.

## :clipboard: Review Checklist
I have added a code shell with following code 
from plotly.offline import init_notebook_mode, iplot
init_notebook_mode(connected=True)

Please make sure to follow our best practices in the [Contributing guidelines](https://github.com/ourownstory/neural_prophet/blob/main/CONTRIBUTING.md).

### CODE REVIEW

**Review by leoniewgnr — CHANGES_REQUESTED** [review]
Hi @vijaybirju, thanks so much for taking this over. Just a question: This change is only for google colab relevant, isn't it? So should we put the two additional lines in the first if-clause, where we check if google.colab is used?

**Comment by noxan** [comment]
I can confirm the same issue with interactive plots in jupyter notebooks locally in vs code - but it's an issue to all notebooks not only this one in particular - #1235

**Comment by vijaybirju** [comment]
it 

> Hi @vijaybirju, thanks so much for taking this over. Just a question: This change is only for google colab relevant, isn't it? So should we put the two additional lines in the first if-clause, where we check if google.colab is used?

it is for Colab and Kaggle. Should I check for both or just for colab

**Comment by vijaybirju** [comment]
@leoniewgnr can you review it now?

**Comment by vijaybirju** [comment]
> I can confirm the same (or at least a similar) issue with interactive plots in jupyter notebooks locally in vs code - but it's an issue to all notebooks not only this one in particular - #1235

yes it happened in Colab and Kaggle environment

**Comment by leoniewgnr** [comment]
@vijaybirju sorry for not coming back to you, please feel free to ping me on slack, I'll respond faster. 
Thanks so much for taking this one, I changed the location of the tutorials (tidying up the docs folder structure). So the notebook doesn't exist anymore at the current location, so I just put your changes in the notebook of the new location.
See https://github.com/ourownstory/neural_prophet/pull/1309

**Pull request closed without merging**
