### PR TITLE
Unified the naming of variables - num and nb

### PR DESCRIPTION
**Pull request by SaumyaBhushan**
[workerB](https://workerb.linearb.io/v2/badge/collaboration-page?magicLinkId=HcN2Wmd)

https://github.com/ourownstory/neural_prophet/issues/969

### CODE REVIEW

**Comment by SaumyaBhushan** [comment]
Hi @karl-richter @noxan ! can you please review the pull request? Please let me know if something else needs to be changed.

**Review by karl-richter — APPROVED** [review]
Looks good from my side! @alfonsogarciadecorral Can you also have a quick look and confirm that the change makes sense? Thanks!

**Comment by alfonsogarciadecorral** [comment]
@karl-richter  all good!

**Comment by ourownstory** [comment]
Thank you @SaumyaBhushan !

**Pull request merged**
