### PR TITLE
[bug] Fix saved model size

### PR DESCRIPTION
**Pull request by leoniewgnr**
## :microscope: Background
See #1415 

## :crystal_ball: Key changes
removed attribute `_trainer`

### CODE REVIEW

**Comment by leoniewgnr** [comment]
I removed some attributes, but really unsure where the data is saved. In `model.logger.history` is saved some big tensor, but the model size is still not the same:
```
2023-09-19 13:04:06 [INFO]: size of saved fitted model: 288791 (test_utils.py:41)
2023-09-19 13:04:06 [INFO]: testing: save forecast model (test_utils.py:45)
2023-09-19 13:04:06 [INFO]: size of saved forecast model: 43850 (test_utils.py:47)
```

**Comment by leoniewgnr** [comment]
I think I found it! In _trainer there was saved some unecessary information!
2023-09-19 13:51:06 [INFO]: size of saved fitted model: 18095 (test_utils.py:43)
2023-09-19 13:51:06 [INFO]: testing: save forecast model (test_utils.py:47)
2023-09-19 13:51:06 [INFO]: size of saved forecast model: 18180 (test_utils.py:50)

**Review by ourownstory — APPROVED** [review]
Good fix! 

Do you think we should just include `"_trainer"` in  `attrs_to_remove = ["trainer"]`?
Or is there a relevant scenario where  `"_trainer"` needs to be saved, but  `"trainer"`  not?
If not, we can skip the 'minimal' option and keep the code more lean.

**Comment by leoniewgnr** [comment]
@ourownstory no probably not, I think so too, we should drop the minimal version and keep the code lean, will change that soon

**Pull request merged**
