### PR TITLE
[refactor] Update python-holidays integration

### PR DESCRIPTION
**Pull request by arkid15r**
## :microscope: Background

Resolves https://github.com/ourownstory/neural_prophet/issues/295

## :crystal_ball: Key changes
  - Bump python-holidays version to 0.20.
  - Migrate to python-holidays as a single source of country holidays.

## :clipboard: Review Checklist
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, added docstrings and data types to function definitions.
- [x] I have added pytests to check whether my feature / fix works.

Please make sure to follow our best practices in the [Contributing guidelines](https://github.com/ourownstory/neural_prophet/blob/main/CONTRIBUTING.md).

### CODE REVIEW

**Review by ourownstory — APPROVED** [review]
@arkid15r  Wonderful, thank you so much for upgrading `holidays` with the needed countries and for updating our use of `holidays`, including tests. 
Much appreciated!

**Comment by arkid15r** [comment]
> @arkid15r Wonderful, thank you so much for upgrading `holidays` with the needed countries and for updating our use of `holidays`, including tests. Much appreciated!

Hi @ourownstory, 
thanks for the quick reply!

I'm not sure whether it's safe to merge the PR? Those failing metrics and windows tests jobs look a bit concerning.

**Review by noxan — APPROVED** [review]
LGTM, thanks for the awesome contribution @arkid15r 👏

**Comment by noxan** [comment]
@arkid15r Those are (sadly) known issues: windows tests failing are tracked in #991 and the metrics do not work on forks #1113 - so I'll go ahead and merge it

**Pull request merged**
