### PR TITLE
[docs] Restructure existing documentation

### PR DESCRIPTION
**Pull request by noxan**
First part of #767

Screenshot 2022-10-28 at 5 31 14 PM

### CODE REVIEW

**Comment by noxan** [comment]
@ourownstory The pull request is ready to be reviewed from my side. Please have a look at the overall new structure of the documentation and let me know if anything needs adjustment. Changing the content and working on the details is a full up pull request, already in draft #836

**Comment by ourownstory** [comment]
@noxan the docs test seems to fail because it tries to import Prophet - do we need Prophet there?

**Comment by Kevin-Chen0** [comment]
Hi @noxan, just to confirm, this PR is only focused on this stem right, and not the page contents themselves?

image

If so, I only have a couple small suggestions for this PR: in the `HOW TO GUIDES` section, change the `Migration guides` to something like `FB Prophet Migration Guides` or `Prophet Migration Guides` so it is clear that the migration is for Facebook Prophet. Also make `Feature guides` and `Application examples` in proper format.

Other than that, LGTM.

**Comment by noxan** [comment]
@Kevin-Chen0 Thanks for the feedback, adjusted the headlines.

**Review by Kevin-Chen0 — APPROVED** [review]
LGTM

**Pull request merged**
