### PR TITLE
[devops] Add ruff github action

### PR DESCRIPTION
**Pull request by noxan**
## :microscope: Background

- Ruff is a new super fast linting tool (could replace flake8 and isort) https://github.com/charliermarsh/ruff

### CODE REVIEW

**Comment by leoniewgnr** [comment]
@noxan why does the linters /ruff test fail?

**Review by ourownstory — APPROVED** [review]
Great upgrade, thank you Richard!

What do you suggest to do about it's list of errors? Should we address all or should we relax what constitutes an error?

**Comment by ourownstory** [comment]
@noxan Might it make sense to also add this to the pre-commit or pre-push hook?

**Comment by noxan** [comment]
We should migrate our pre-commit hooks to https://pre-commit.com/ - great idea to include it there too.

We might be able to drop flake8 and isort over time (to be replaced by ruff).

Regarding the warnings: So far we excluded the `tests` folder. Ruff also has an autofix feature, I've pushed things to a branch here: https://github.com/ourownstory/neural_prophet/compare/ruff-fixes?expand=1

**Pull request merged**
