### PR TITLE
[feature] separate panel uncertainty plot

### PR DESCRIPTION
**Pull request by LeonieFreisinger**
Referencing issue #710 
**Problem**
The plot() function already includes plotting the uncertainty. However, the plot_components() function does not include plotting the uncertainty of yhat as a component. 

**Solution**
Modify the plot_components() function to plot the uncertainty of yhat as a component in a separate panel. Therefore, the matplotlib and plotly version will be modified. The uncertainty will be plotted with the x-axis = 0.5 quantile as reference.

### CODE REVIEW

**Comment by Kevin-Chen0** [comment]
Thanks for all your work @LeonieFreisinger! I'll review this shortly and will give you feedback if any.

**Comment by LeonieFreisinger** [comment]
@Kevin-Chen0 Thanks a lot!! :) I just added an additional test in test_plotting.py to improve code cov.

**Comment by ourownstory** [comment]
Some improvement ideas:
* Use same color schema as in main uncertainty plotting (as in plotly)

**Comment by Kevin-Chen0** [comment]
Hey Leonie, maybe you can also modify the [uncertainty_estimation_peyton_manning.ipynb](https://github.com/ourownstory/neural_prophet/blob/main/tutorials/feature-use/uncertainty_estimation_peyton_manning.ipynb) example notebook so the `m.plot_components(forecast)` are so plotting the uncertainties.

**Comment by Kevin-Chen0** [comment]
Also, should the `m.plot_parameters()` include uncertainty as well or just `m.plot_components(forecast)`?

**Comment by LeonieFreisinger** [comment]
@Kevin-Chen0 @ourownstory thanks a lot!
I will modify the notebook. I think the uncertainties shouldn´t be in the `m.plot_parameters() `

**Comment by LeonieFreisinger** [comment]
@ourownstory code check fails because of test_regularization_lagged_regressor. This should be fixed when merging #794 into main and rebasing this branch.

**Comment by ourownstory** [comment]
> Also, should the `m.plot_parameters()` include uncertainty as well or just `m.plot_components(forecast)`?

we could allow the user to decide to plot a specific percentile, instead of hard-coding the mean.

**Review by ourownstory — CHANGES_REQUESTED** [review]
In all your string formatings, please use f-strings.

**Comment by ourownstory** [comment]
Please also remove warnings printouts from the tutorial notebooks.

**Comment by LeonieFreisinger** [comment]
>>> Also, should the `m.plot_parameters()` include uncertainty as well or just `m.plot_components(forecast)`?
>>
>>we could allow the user to decide to plot a specific percentile, instead of hard-coding the mean.
>>
> okay. I would suggest following up on that feature in a new PR. Is that okay?

**Pull request merged**
