### PR TITLE
 replace the os module with pathlib module in code

### PR DESCRIPTION
**Pull request by newturok**
## :microscope: Background
just make code cleaner

## :clipboard: Review Checklist
- [X] I have performed a self-review of my own code.
- [ ] I have commented my code, added docstrings and data types to function definitions.
- [ ] I have added pytests to check whether my feature / fix works.

Please make sure to follow our best practices in the [Contributing guidelines](https://github.com/ourownstory/neural_prophet/blob/main/CONTRIBUTING.md).

### CODE REVIEW

**Comment by leoniewgnr** [comment]
@newturok thanks for this PR, are you still working on it? Or do you need help?

**Comment by newturok** [comment]
@leoniewgnr right now you can accept this
Maybe later I will make more ajustments

**Comment by leoniewgnr** [comment]
@newturok can you explain the changes? whats the difference to the old version?

**Comment by leoniewgnr** [comment]
closed due to inactivity, if you want to continue working on this feel free to re-open it

**Pull request closed without merging**
