### PR TITLE
[lightning] Load best model if not latest

### PR DESCRIPTION
**Pull request by karl-richter**
If the latest model during training is not the best, load the best model from checkpoint.

### CODE REVIEW

**Comment by karl-richter** [comment]
note to self: redo changes in clean PR.

**Comment by Kevin-Chen0** [comment]
Should this still be in version 0.5.0?

**Comment by karl-richter** [comment]
Due to the merge of Lightning into main, the git hash relations of this pr are messed up. This pr should be closed and a new pr should be opened that contains a clean implementation of the feature.

**Comment by karl-richter** [comment]
Will be solved by #999

**Pull request closed without merging**
