### PR TITLE
Change str.format() to f-string

### PR DESCRIPTION
**Pull request by YoussefKafa**
**issue: #755**
Change str.format() to f-string throughout the neuralprophet source code.

### CODE REVIEW

**Comment by ourownstory** [comment]
@YoussefKafa Thank you for your contribution!

It looks good to me to be merged after addressing:
1) merge conflicts
2) remove all edits of benchmark.py and related files (e.g. tests) and do a PR for those in https://github.com/ourownstory/test-of-time

**Review by ourownstory — CHANGES_REQUESTED** [review]
@YoussefKafa Thank you for your contribution!

It looks good to me to be merged after addressing:
1) merge conflicts
2) remove all edits of benchmark.py and related files (e.g. tests) and do a PR for those in https://github.com/ourownstory/test-of-time

**Comment by Kevin-Chen0** [comment]
Hi @YoussefKafa, just wanted to follow up regarding resolving the merge conflict. Do you need any assistance with that? Thanks

**Comment by YoussefKafa** [comment]
I'm really sorry , I have been very lately last week. So Yes please , I need help addressing : 
-merge conflicts
-remove all edits of benchmark.py and related files (e.g. tests) and do a PR for those in https://github.com/ourownstory/test-of-time
And I will continue contributing to this great project as soon as I can.
Thank you.

**Comment by Kevin-Chen0** [comment]
I have just created a new [PR](https://github.com/ourownstory/neural_prophet/pull/773) and will move all of your code there.

Thanks for all of your contributions to this issue Youssef!

**Pull request closed without merging**
