### PR TITLE
Rename plot_forecast.py and plot_model_parameters.py to xxx_matplotli…

### PR DESCRIPTION
**Pull request by SaumyaBhushan**
Rename plot_forecast.py and plot_model_parameters.py to plot_forecast._matplotlib.py and plot_model_parameters_matplotlib.py to be consistent

https://github.com/ourownstory/neural_prophet/issues/964

### CODE REVIEW

**Comment by SaumyaBhushan** [comment]
@LeonieFreisinger model / metrics (pull_request) is failing . Can you please help ?

**Comment by LeonieFreisinger** [comment]
> @LeonieFreisinger model / metrics (pull_request) is failing . Can you please help ?

@SaumyaBhushan sorry for the late reply. The metric test currently fails in some PRs. However, there is already a fix on the cml repo https://github.com/iterative/cml/pull/1228. As soon as this PR will be deployed, the error will resolve.
The rest is looking good and your PR can be merged.

**Review by LeonieFreisinger — COMMENTED** [review]
@Kevin-Chen0 @ourownstory the PR is looking good, feel free to merge it. Thank you!

**Review by LeonieFreisinger — APPROVED** [review]

**Comment by noxan** [comment]
@SaumyaBhushan could you please resolve the merge conflict? happy to merge it right after - best tag me directly, many thanks.

**Comment by Kevin-Chen0** [comment]
@SaumyaBhushan @LeonieFreisinger Can you resolve this merge conflict?

**Comment by SaumyaBhushan** [comment]
Hi @LeonieFreisinger Can you please help me in resolving these conflicts?

**Comment by noxan** [comment]
@SaumyaBhushan don't worry about the merge conflict no more - thanks for your contribution :)

**Comment by SaumyaBhushan** [comment]
Thanks alot @noxan

**Pull request merged**
