### PR TITLE
Add pull request template for Github

### PR DESCRIPTION
**Pull request by karl-richter**
## :microscope: Background

- Why is this change needed? Is there a related issue or a new feature to be added?

## :crystal_ball: Key changes

- Explain the main changes introduced by this pull request for the reviewer.

## :clipboard: Review Checklist
- [ ] I have performed a self-review of my own code.
- [ ] I have commented my code, added docstrings and data types to function definitions.
- [ ] I have added pytests to check whether my feature / fix works.

Please make sure to follow our best practices in the [Contributing guidelines](https://github.com/ourownstory/neural_prophet/blob/main/CONTRIBUTING.md).

### CODE REVIEW

**Comment by karl-richter** [comment]
@ourownstory @noxan @Kevin-Chen0 what do you think, should we add a pr template like this to better structure the pr review? (the icons are debatable)

**Comment by noxan** [comment]
@karl-richter I like the idea very much, great initiative. A bit of feedback and open ended questions from my side:
1. I wouldn't know what to put under status quo - I mean in contrast to what I write in key changes -> maybe I didn't get it, otherwise I'd rather remove this section
2. The list of checks sounds nice, yet most of them should be obvious in the sense you do not have to manually check them, e.g. follow contribution guidelines, or checks are passing - would propose to reduce this list to the actual actionable items. Possibly some general guide we could link to in contribution instructions might be great.

**Comment by Kevin-Chen0** [comment]
> @karl-richter I like the idea very much, great initiative. A bit of feedback and open ended questions from my side:
> 
> 1. I wouldn't know what to put under status quo - I mean in contrast to what I write in key changes -> maybe I didn't get it, otherwise I'd rather remove this section
> 2. The list of checks sounds nice. Would propose to reduce this list to the actual actionable items. Possibly some general guide we could link in contribution instructions might be great (e.g. passing github actions, code formatting, etc)
> 3. ~Not exactly related to this pull request, yet kind of in line with your original idea to improve PR reviews: is there any way to reduce the number of automated posts (performance, codecov, etc) on each pull request, make the content of them collapsible or link to somewhere else? I feel like it's quite hard to see the actual review discussion with that much "noise"~ now part of [[dev-ops] Collapsible metrics reports #926](https://github.com/ourownstory/neural_prophet/pull/926)
> 4. In line with point 3, does this codecov check add any value?
> 
> Happy to follow up, like your initiative :)

I agree with Richard, and propose the following:

- Rename **Status Quo** to something like **Issue**, which detail the underlying issue or problem that the PR is trying to fix. If there is already a linked Issue, then you can simply write "See Development". This can be an optional section.
- **Key Changes** is fine.
- Add the following below to the **Review Checklist** (if you think it is needed):

- I have resolved any merge conflicts.
- I have tagged at least one Reviewer and selected a sprint milestone.
- The Status label is set to "Status: Needs Reviewer" or "Status: Ready".

**Review by noxan — CHANGES_REQUESTED** [review]
@karl-richter just marking this one as `changes requested` based on kevin's feedback

**Comment by karl-richter** [comment]
> > @karl-richter I like the idea very much, great initiative. A bit of feedback and open ended questions from my side:
> > 
> > 1. I wouldn't know what to put under status quo - I mean in contrast to what I write in key changes -> maybe I didn't get it, otherwise I'd rather remove this section
> > 2. The list of checks sounds nice. Would propose to reduce this list to the actual actionable items. Possibly some general guide we could link in contribution instructions might be great (e.g. passing github actions, code formatting, etc)
> > 3. ~Not exactly related to this pull request, yet kind of in line with your original idea to improve PR reviews: is there any way to reduce the number of automated posts (performance, codecov, etc) on each pull request, make the content of them collapsible or link to somewhere else? I feel like it's quite hard to see the actual review discussion with that much "noise"~ now part of [[dev-ops] Collapsible metrics reports #926](https://github.com/ourownstory/neural_prophet/pull/926)
> > 4. In line with point 3, does this codecov check add any value?
> > 
> > Happy to follow up, like your initiative :)
> 
> I agree with Richard, and propose the following:
> 
> * Rename **Status Quo** to something like **Issue**, which detail the underlying issue or problem that the PR is trying to fix. If there is already a linked Issue, then you can simply write "See Development". This can be an optional section.
> * **Key Changes** is fine.
> * Add the following below to the **Review Checklist** (if you think it is needed):
> * I have resolved any merge conflicts.
> * I have tagged at least one Reviewer and selected a sprint milestone.
> * The Status label is set to "Status: Needs Reviewer" or "Status: Ready".

Thanks for your feedback! I adopted the first part, but Richard and I decided to not add the info with the status label and milestone since only the dev-core team has the rights to do so.

**Review by noxan — APPROVED** [review]

**Pull request merged**
