### PR TITLE
Fix - loading model on machine with diffrent accelerator

### PR DESCRIPTION
**Pull request by McOffsky**
## :microscope: Background

During my experiments with NP I've found out, that utils.load() is using trainer config is retrived from model, including accelerator. This caused an error on cpu machine while loading model fitted on GPU.

## :crystal_ball: Key changes

- NeuralProphet.restore_trainer() now takes optional argument, accelerator: str = None. If not provided, value stored in model will be used.

- utils.load() now creates torch.device(map_location) into separate variable, and that variable is used in torch.load(). Orginal value is additionaly passed to NeuralProphet.restore_trainer() as accelerator

## :clipboard: Review Checklist
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, added docstrings and data types to function definitions.
- [n/c] I have added pytests to check whether my feature / fix works.

Please make sure to follow our best practices in the [Contributing guidelines](https://github.com/ourownstory/neural_prophet/blob/main/CONTRIBUTING.md).

### CODE REVIEW

**Review by ourownstory — APPROVED** [review]
Great addition, thank you!

**Comment by ourownstory** [comment]
Can be merged after passing of tests.

**Comment by McOffsky** [comment]
Happy to help with such great library! 
I'll fix the issues tomorrow, it'a a bit late in my timezone ;)

**Comment by ourownstory** [comment]
Hi @McOffsky Thank you!
The failed tests are not related to your contribution, we can safely ignore them. 

The pyright type checker did want a change of line 2737, I fixed it quickly - save your efforts for a later contribution. 
(For your reference you can read about the type logic here: https://stackoverflow.com/questions/51710037/how-should-i-use-the-optional-type-hint)

Best, 
Oskar

**Comment by ourownstory** [comment]
Update: waiting for rerun of tests to finish before merge.

**Pull request merged**
