### PR TITLE
Improve github action speed for docs test

### PR DESCRIPTION
**Pull request by noxan**
- Use pip cache in docs test github action (reduces runtime by ~2x, from [4.5 minutes](https://github.com/ourownstory/neural_prophet/actions/runs/3390851468) down to [2.5 minutes](https://github.com/ourownstory/neural_prophet/actions/runs/3412958287))

### CODE REVIEW

**Comment by karl-richter** [comment]
Really good idea! Can we also add this to the other tests that use the pip requirements file? eg. the metrics.yml test.

**Comment by noxan** [comment]
@karl-richter yes, we could, I'd also support the idea. happy to follow up on this, might make sense to fix our dependency versions along that task.

**Comment by Kevin-Chen0** [comment]
Is this for version 0.5.0?

**Review by karl-richter — APPROVED** [review]
lgtm

**Pull request merged**
